services:
  web:
    build: .
    ports:
      - "8000:8000"  # FastAPI exposed on port 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase  # Connects to db service
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 4000
